### ISSUE TITLE
Failed to re-import Platform into System

### ISSUE THREAD

**Issue by matthiasFrei** [systemviewinc/visual-system-integrator#11] opened 2017-05-17 07:08 UTC
### Problem
When the platform is re-compiled and re-imported the following error is shown:

```
vsi_compile_platform {/home/frma/Documents/Projekte/project01/project01.srcs/sources_1/bd/platform/platform.bd}
vsi_import_platform {/home/frma/Documents/Projekte/project01/project01.srcs/sources_1/bd/platform/platform.bd}
failed import. The design "platform" is not a valid vsi_system design
```

### Reason:

The system is in a unsaved status (shown with the *)
-> Save the system and the re-import should work

**Comment by udnaan** [comment] 2017-05-17 18:14
hi @matthiasFrei 

The issue is due to system canvas not being active. The underlying issue is in Vivado. This can be avoided by using the `sources tab->double click [system name]` or `menu->open system->[system name]`

Also see the workaround here http://docs.systemviewinc.com/troubleshooting/readme.html#general

Closing it as we have a workaround.

**Closed as completed by udnaan** 2017-05-17 18:14 UTC
